/* The following code was generated by JFlex 1.7.0 */

package ubordeaux.deptinfo.compilation.project.main;

import beaver.Symbol;
import beaver.Scanner;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/autofs/unitytravail/travail/tfurelaud/eclipse/projcomp/projcomp/scanner/Scanner.jflex</tt>
 */
class ScannerExp extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\62\1\5\1\6\1\6\1\6\22\0\1\62\1\27\1\7"+
    "\3\0\1\35\1\0\1\22\1\23\1\4\1\13\1\21\1\14\1\17"+
    "\1\3\1\10\11\1\1\16\1\15\1\25\1\24\1\26\2\0\6\12"+
    "\21\2\1\11\2\2\1\32\1\0\1\33\1\20\2\0\1\52\1\60"+
    "\1\51\1\45\1\40\1\37\1\57\1\44\1\36\2\2\1\41\1\2"+
    "\1\50\1\46\1\55\1\2\1\56\1\42\1\47\1\53\1\61\1\43"+
    "\1\11\1\54\1\2\1\30\1\34\1\31\7\0\1\6\32\0\1\62"+
    "\u15df\0\1\62\u097f\0\13\62\35\0\1\6\1\6\5\0\1\62\57\0"+
    "\1\62\u0fa0\0\1\62\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\2\1\7\1\10\1\11\1\12\1\1\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\1\17\3\3\0\1\27\1\3\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\12\3"+
    "\1\40\1\41\14\3\1\0\1\42\4\3\1\43\10\3"+
    "\1\44\11\3\1\45\1\6\3\3\1\46\6\3\1\47"+
    "\1\50\1\51\1\52\1\53\10\3\1\54\4\3\1\55"+
    "\2\3\1\56\1\57\3\3\1\60\3\3\1\61\1\62"+
    "\1\63\4\3\1\64\1\65\1\3\1\66\1\3\1\67"+
    "\1\70\1\57\1\3\1\71\1\72\1\3\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\63\0\63\0\377"+
    "\0\u0132\0\63\0\63\0\63\0\63\0\u0165\0\63\0\63"+
    "\0\63\0\63\0\u0198\0\u01cb\0\u01fe\0\u0231\0\63\0\63"+
    "\0\63\0\63\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363"+
    "\0\u0396\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb"+
    "\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa\0\377\0\63\0\u062d"+
    "\0\63\0\63\0\63\0\63\0\63\0\63\0\63\0\231"+
    "\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u07f8\0\u082b\0\231\0\231\0\u085e\0\u0891\0\u08c4\0\u08f7"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f"+
    "\0\u0ac2\0\u062d\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\231\0\u0bc1"+
    "\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\231"+
    "\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58\0\u0e8b\0\u0ebe"+
    "\0\u0ef1\0\231\0\u05fa\0\u0f24\0\u0f57\0\u0f8a\0\231\0\u0fbd"+
    "\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc\0\231\0\231\0\231"+
    "\0\231\0\231\0\u10ef\0\u1122\0\u1155\0\u1188\0\u11bb\0\u11ee"+
    "\0\u1221\0\u1254\0\231\0\u1287\0\u12ba\0\u12ed\0\u1320\0\231"+
    "\0\u1353\0\u1386\0\231\0\u13b9\0\u13ec\0\u141f\0\u1452\0\231"+
    "\0\u1485\0\u14b8\0\u14eb\0\231\0\231\0\231\0\u151e\0\u1551"+
    "\0\u1584\0\u15b7\0\231\0\231\0\u15ea\0\231\0\u161d\0\231"+
    "\0\231\0\231\0\u1650\0\231\0\231\0\u1683\0\231";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\11"+
    "\2\4\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\4"+
    "\1\40\1\41\1\4\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\2\4\1\50\1\51\1\4\1\52\1\53\1\7"+
    "\64\0\1\3\1\4\5\0\1\3\2\4\23\0\24\4"+
    "\2\0\2\4\5\0\3\4\23\0\24\4\4\0\1\54"+
    "\1\55\56\0\7\56\1\57\53\56\1\0\1\3\1\4"+
    "\5\0\1\3\1\60\1\4\23\0\24\4\20\0\1\61"+
    "\67\0\1\62\62\0\1\63\62\0\1\64\62\0\1\65"+
    "\72\0\1\66\63\0\1\67\26\0\2\4\5\0\3\4"+
    "\23\0\1\4\1\70\10\4\1\71\11\4\2\0\2\4"+
    "\5\0\3\4\23\0\14\4\1\72\1\73\6\4\2\0"+
    "\2\4\5\0\3\4\23\0\3\4\1\74\6\4\1\75"+
    "\11\4\2\0\2\4\5\0\3\4\23\0\5\4\1\76"+
    "\3\4\1\77\12\4\2\0\2\4\5\0\3\4\23\0"+
    "\6\4\1\100\15\4\2\0\2\4\5\0\3\4\23\0"+
    "\1\101\1\4\1\102\5\4\1\103\13\4\2\0\2\4"+
    "\5\0\3\4\23\0\1\4\1\104\22\4\2\0\2\4"+
    "\5\0\3\4\23\0\6\4\1\105\7\4\1\106\1\4"+
    "\1\107\3\4\2\0\2\4\5\0\3\4\23\0\2\4"+
    "\1\110\12\4\1\111\6\4\2\0\2\4\5\0\3\4"+
    "\23\0\14\4\1\112\7\4\2\0\2\4\5\0\3\4"+
    "\23\0\20\4\1\113\3\4\2\0\2\4\5\0\3\4"+
    "\23\0\20\4\1\114\3\4\2\0\2\4\5\0\3\4"+
    "\23\0\2\4\1\115\21\4\2\0\2\4\5\0\3\4"+
    "\23\0\2\4\1\116\5\4\1\117\13\4\2\0\2\4"+
    "\5\0\3\4\23\0\14\4\1\120\7\4\1\0\5\54"+
    "\1\7\1\0\54\54\4\55\1\121\1\55\1\0\54\55"+
    "\1\0\1\122\1\4\5\0\1\122\1\4\1\122\23\0"+
    "\1\4\2\122\4\4\1\122\3\4\2\122\5\4\1\122"+
    "\1\4\2\0\2\4\5\0\3\4\23\0\11\4\1\123"+
    "\12\4\2\0\2\4\5\0\3\4\23\0\3\4\1\124"+
    "\20\4\2\0\2\4\5\0\3\4\23\0\12\4\1\125"+
    "\11\4\2\0\2\4\5\0\3\4\23\0\4\4\1\126"+
    "\17\4\2\0\2\4\5\0\3\4\23\0\7\4\1\127"+
    "\14\4\2\0\2\4\5\0\3\4\23\0\1\130\23\4"+
    "\2\0\2\4\5\0\3\4\23\0\20\4\1\131\3\4"+
    "\2\0\2\4\5\0\3\4\23\0\1\132\23\4\2\0"+
    "\2\4\5\0\3\4\23\0\4\4\1\133\17\4\2\0"+
    "\2\4\5\0\3\4\23\0\1\4\1\134\22\4\2\0"+
    "\2\4\5\0\3\4\23\0\2\4\1\135\21\4\2\0"+
    "\2\4\5\0\3\4\23\0\17\4\1\136\4\4\2\0"+
    "\2\4\5\0\3\4\23\0\15\4\1\137\6\4\2\0"+
    "\2\4\5\0\3\4\23\0\5\4\1\140\16\4\2\0"+
    "\2\4\5\0\3\4\23\0\3\4\1\141\20\4\2\0"+
    "\2\4\5\0\3\4\23\0\4\4\1\142\17\4\2\0"+
    "\2\4\5\0\3\4\23\0\20\4\1\143\3\4\2\0"+
    "\2\4\5\0\3\4\23\0\1\144\7\4\1\145\13\4"+
    "\2\0\2\4\5\0\3\4\23\0\11\4\1\146\2\4"+
    "\1\147\7\4\2\0\2\4\5\0\3\4\23\0\21\4"+
    "\1\150\2\4\2\0\2\4\5\0\3\4\23\0\10\4"+
    "\1\151\13\4\2\0\2\4\5\0\3\4\23\0\20\4"+
    "\1\152\3\4\1\0\3\55\1\153\1\121\1\55\1\0"+
    "\54\55\1\0\2\4\5\0\3\4\23\0\2\4\1\154"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\4\4\1\155"+
    "\17\4\2\0\2\4\5\0\3\4\23\0\13\4\1\156"+
    "\10\4\2\0\2\4\5\0\3\4\23\0\2\4\1\157"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\11\4\1\160"+
    "\12\4\2\0\2\4\5\0\3\4\23\0\1\161\14\4"+
    "\1\162\6\4\2\0\2\4\5\0\3\4\23\0\3\4"+
    "\1\163\20\4\2\0\2\4\5\0\3\4\23\0\17\4"+
    "\1\164\4\4\2\0\2\4\5\0\3\4\23\0\14\4"+
    "\1\165\7\4\2\0\2\4\5\0\3\4\23\0\12\4"+
    "\1\166\11\4\2\0\2\4\5\0\3\4\23\0\2\4"+
    "\1\167\21\4\2\0\2\4\5\0\3\4\23\0\2\4"+
    "\1\170\21\4\2\0\2\4\5\0\3\4\23\0\3\4"+
    "\1\171\20\4\2\0\2\4\5\0\3\4\23\0\2\4"+
    "\1\172\21\4\2\0\2\4\5\0\3\4\23\0\14\4"+
    "\1\173\7\4\2\0\2\4\5\0\3\4\23\0\12\4"+
    "\1\174\11\4\2\0\2\4\5\0\3\4\23\0\13\4"+
    "\1\175\10\4\2\0\2\4\5\0\3\4\23\0\15\4"+
    "\1\176\6\4\2\0\2\4\5\0\3\4\23\0\7\4"+
    "\1\177\14\4\2\0\2\4\5\0\3\4\23\0\1\200"+
    "\23\4\2\0\2\4\5\0\3\4\23\0\3\4\1\201"+
    "\20\4\2\0\2\4\5\0\3\4\23\0\21\4\1\202"+
    "\2\4\2\0\2\4\5\0\3\4\23\0\2\4\1\203"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\11\4\1\204"+
    "\12\4\2\0\2\4\5\0\3\4\23\0\13\4\1\205"+
    "\10\4\2\0\2\4\5\0\3\4\23\0\12\4\1\206"+
    "\11\4\2\0\2\4\5\0\3\4\23\0\13\4\1\207"+
    "\10\4\2\0\2\4\5\0\3\4\23\0\2\4\1\210"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\10\4\1\211"+
    "\13\4\2\0\2\4\5\0\3\4\23\0\15\4\1\212"+
    "\6\4\2\0\2\4\5\0\3\4\23\0\16\4\1\213"+
    "\5\4\2\0\2\4\5\0\3\4\23\0\11\4\1\214"+
    "\12\4\2\0\2\4\5\0\3\4\23\0\2\4\1\215"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\20\4\1\216"+
    "\3\4\2\0\2\4\5\0\3\4\23\0\3\4\1\217"+
    "\20\4\2\0\2\4\5\0\3\4\23\0\12\4\1\220"+
    "\11\4\2\0\2\4\5\0\3\4\23\0\2\4\1\221"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\2\4\1\222"+
    "\21\4\2\0\2\4\5\0\3\4\23\0\1\223\23\4"+
    "\2\0\2\4\5\0\3\4\23\0\6\4\1\224\15\4"+
    "\2\0\2\4\5\0\3\4\23\0\21\4\1\225\2\4"+
    "\2\0\2\4\5\0\3\4\23\0\11\4\1\226\12\4"+
    "\2\0\2\4\5\0\3\4\23\0\4\4\1\227\17\4"+
    "\2\0\2\4\5\0\3\4\23\0\3\4\1\230\20\4"+
    "\2\0\2\4\5\0\3\4\23\0\3\4\1\231\20\4"+
    "\2\0\2\4\5\0\3\4\23\0\7\4\1\232\14\4"+
    "\2\0\2\4\5\0\3\4\23\0\12\4\1\233\11\4"+
    "\2\0\2\4\5\0\3\4\23\0\12\4\1\234\11\4"+
    "\2\0\2\4\5\0\3\4\23\0\14\4\1\235\7\4"+
    "\2\0\2\4\5\0\3\4\23\0\20\4\1\236\3\4"+
    "\2\0\2\4\5\0\3\4\23\0\10\4\1\237\13\4"+
    "\2\0\2\4\5\0\3\4\23\0\2\4\1\240\21\4"+
    "\2\0\2\4\5\0\3\4\23\0\11\4\1\241\12\4"+
    "\2\0\2\4\5\0\3\4\23\0\12\4\1\242\11\4"+
    "\2\0\2\4\5\0\3\4\23\0\15\4\1\243\6\4"+
    "\2\0\2\4\5\0\3\4\23\0\12\4\1\244\11\4"+
    "\2\0\2\4\5\0\3\4\23\0\12\4\1\245\11\4"+
    "\2\0\2\4\5\0\3\4\23\0\20\4\1\246\3\4"+
    "\2\0\2\4\5\0\3\4\23\0\2\4\1\247\21\4"+
    "\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5814];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\2\11\2\1\4\11\1\1\4\11"+
    "\4\1\4\11\21\1\3\0\1\11\1\1\7\11\31\1"+
    "\1\0\126\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    // Petit helpers pour simplifier la création de token.
    // On retient la position de chaque token pour la gestion d'erreur
    // voir beaver-rt/src/main/java/beaver/Symbol.java
    private Symbol newToken(short id)
    {
        return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), null);
    }

    private Symbol newToken(short id, Object value)
    {
        return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  ScannerExp(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {     return new Symbol(Terminals.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Scanner.Exception("caractère inattendu '" + yytext() + "'");
            } 
            // fall through
          case 60: break;
          case 2: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LIT_INTEGER, Integer.parseInt(yytext()));
            } 
            // fall through
          case 61: break;
          case 3: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_IDENTIFIER, yytext());
            } 
            // fall through
          case 62: break;
          case 4: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_DIV);
            } 
            // fall through
          case 63: break;
          case 5: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_TIMES);
            } 
            // fall through
          case 64: break;
          case 6: 
            { 
            } 
            // fall through
          case 65: break;
          case 7: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_PLUS);
            } 
            // fall through
          case 66: break;
          case 8: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_MINUS);
            } 
            // fall through
          case 67: break;
          case 9: 
            { System.out.println(yytext());return newToken(Terminals.TOKEN_SEMIC);
            } 
            // fall through
          case 68: break;
          case 10: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_COLON);
            } 
            // fall through
          case 69: break;
          case 11: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_CIRC);
            } 
            // fall through
          case 70: break;
          case 12: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_COMMA);
            } 
            // fall through
          case 71: break;
          case 13: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LPAR);
            } 
            // fall through
          case 72: break;
          case 14: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_RPAR);
            } 
            // fall through
          case 73: break;
          case 15: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_AFF);
            } 
            // fall through
          case 74: break;
          case 16: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LT);
            } 
            // fall through
          case 75: break;
          case 17: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_GT);
            } 
            // fall through
          case 76: break;
          case 18: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_NOT);
            } 
            // fall through
          case 77: break;
          case 19: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LBRACE);
            } 
            // fall through
          case 78: break;
          case 20: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_RBRACE);
            } 
            // fall through
          case 79: break;
          case 21: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LBRACKET);
            } 
            // fall through
          case 80: break;
          case 22: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_RBRACKET);
            } 
            // fall through
          case 81: break;
          case 23: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LIT_STRING, yytext());
            } 
            // fall through
          case 82: break;
          case 24: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_DOTDOT);
            } 
            // fall through
          case 83: break;
          case 25: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_EQ);
            } 
            // fall through
          case 84: break;
          case 26: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LE);
            } 
            // fall through
          case 85: break;
          case 27: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_GE);
            } 
            // fall through
          case 86: break;
          case 28: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_NE);
            } 
            // fall through
          case 87: break;
          case 29: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_OR);
            } 
            // fall through
          case 88: break;
          case 30: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_AND);
            } 
            // fall through
          case 89: break;
          case 31: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_IF);
            } 
            // fall through
          case 90: break;
          case 32: 
            { System.out.println(yytext());return newToken(Terminals.TOKEN_DO);
            } 
            // fall through
          case 91: break;
          case 33: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_OF);
            } 
            // fall through
          case 92: break;
          case 34: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_LIT_INTEGER, Integer.parseInt(yytext().replace("0x",""),16));
            } 
            // fall through
          case 93: break;
          case 35: 
            { System.out.println(yytext());return newToken(Terminals.TOKEN_END);
            } 
            // fall through
          case 94: break;
          case 36: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_NEW);
            } 
            // fall through
          case 95: break;
          case 37: 
            { System.out.print(yytext() + " ");return newToken(Terminals.TOKEN_VAR);
            } 
            // fall through
          case 96: break;
          case 38: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_ELSE);
            } 
            // fall through
          case 97: break;
          case 39: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_THEN);
            } 
            // fall through
          case 98: break;
          case 40: 
            { System.out.print(yytext() + " ");return newToken(Terminals.TOKEN_TYPE);
            } 
            // fall through
          case 99: break;
          case 41: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_TRUE);
            } 
            // fall through
          case 100: break;
          case 42: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_NULL);
            } 
            // fall through
          case 101: break;
          case 43: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_CASE);
            } 
            // fall through
          case 102: break;
          case 44: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_FALSE);
            } 
            // fall through
          case 103: break;
          case 45: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_WHILE);
            } 
            // fall through
          case 104: break;
          case 46: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_ARRAY);
            } 
            // fall through
          case 105: break;
          case 47: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_PRINTLN);
            } 
            // fall through
          case 106: break;
          case 48: 
            { System.out.println(yytext());return newToken(Terminals.TOKEN_BEGIN);
            } 
            // fall through
          case 107: break;
          case 49: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_SWITCH);
            } 
            // fall through
          case 108: break;
          case 50: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_STRING);
            } 
            // fall through
          case 109: break;
          case 51: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_STRUCT);
            } 
            // fall through
          case 110: break;
          case 52: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_RETURN);
            } 
            // fall through
          case 111: break;
          case 53: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_READLN);
            } 
            // fall through
          case 112: break;
          case 54: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_INTEGER);
            } 
            // fall through
          case 113: break;
          case 55: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_DISPOSE);
            } 
            // fall through
          case 114: break;
          case 56: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_DEFAULT);
            } 
            // fall through
          case 115: break;
          case 57: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_BOOLEAN);
            } 
            // fall through
          case 116: break;
          case 58: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_FUNCTION);
            } 
            // fall through
          case 117: break;
          case 59: 
            { System.out.print(yytext());return newToken(Terminals.TOKEN_PROCEDURE);
            } 
            // fall through
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
